### ISSUE TITLE
testacular / karma config files

### ISSUE THREAD

**Issue by ghost** [StarterSquad/ngseed#1]
thanks for sharing your seed. I tried it. Most works pretty will. The config files for karma in the test folder start with "testacular". I guess you did not update them. They do not work on my ubuntu / Chrome platform.

here is what I get:
Chrome 30.0 (Linux) ERROR
    Uncaught Error: Script error
    http://requirejs.org/docs/errors.html#scripterror
    at http://localhost:9876/adapter/lib/require.js?1365839185000:1746
Chrome 30.0 (Linux): Executed 0 of 0 ERROR (0.249 secs / 0 secs)

I tried updating to the latest karma version and now I get:
karma start ./tests/testacular-build.conf.js --browsers Chrome
WARN [config]: JASMINE is not supported anymore.
    Please use `frameworks = ["jasmine"];` instead.
WARN [config]: JASMINE_ADAPTER is not supported anymore.
    Please use `frameworks = ["jasmine"];` instead.
WARN [config]: REQUIRE is not supported anymore.
    Please use `frameworks = ["requirejs"];` instead.
WARN [config]: REQUIRE_ADAPTER is not supported anymore.
    Please use `frameworks = ["requirejs"];` instead.
WARN [config]: LOG_INFO is not supported anymore.
  Please use `karma.LOG_INFO` instead.
ERROR [config]: Config file must export a function!
  module.exports = function(config) {
    config.set({
      // your config
    });
  };

**Comment by dmitryevseev** [comment]
Hi @markfink thank you very much for feedback.
You're right there are issues running it with `karma` command, I got used to run tests with grunt and didn't notice that for a while. And even now `grunt karma` still doing its job.

Anyway, I'll take a look and fix that as soon as possible.

**Comment by ghost** [comment]
hmm, testing the compiled version is not even contained in Gruntfile.js

**Comment by dmitryevseev** [comment]
Hey @markfink . I've updated karma configs to work with karma 0.10 . But unfortunately there is still issue with running tests on compiled code. I'm still looking for a solution, will keep you posted

**Comment by dmitryevseev** [comment]
Whoops missed push. Now code is on its place

**Comment by ghost** [comment]
the update is good but I still get many errors:

Running "karma:ci" (karma) task
INFO [karma]: Karma v0.10.1 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.1 (Linux)]: Connected on socket id VTP0TUFxIyaL7DwqP0up
ERROR: 'There is no timestamp for base/build/js/main.js!'
ERROR: 'There is no timestamp for base/tests/specs/services/index.js!'
ERROR: 'There is no timestamp for base/tests/specs/filters/index.js!'
ERROR: 'There is no timestamp for base/tests/specs/directives/index.js!'
ERROR: 'There is no timestamp for base/tests/specs/controllers/index.js!'
ERROR: 'There is no timestamp for base/source/js/libs/angular/angular.js!'
ERROR: 'There is no timestamp for base/tests/specs/controllers/home-ctrl-spec.js!'
PhantomJS 1.9.1 (Linux): Executed 0 of 0
ERROR: 'There is no timestamp for base/source/js/libs/angular/1.1.3/angular-mocks.js!'
PhantomJS 1.9.1 (Linux): Executed 0 of 0
ERROR: 'There is no timestamp for base/libs/requirejs-domready/domReady.js!'
ERROR: 'There is no timestamp for base/source/js/libs/chai/chai.js!'
PhantomJS 1.9.1 (Linux) ERROR
    Error: Script error for: angular-mocks
    http://requirejs.org/docs/errors.html#scripterror
    at /home/mark/sandbox/angularjs-requirejs-seed/node_modules/karma-requirejs/lib/require.js:138
PhantomJS 1.9.1 (Linux) ERROR
    Error: Script error for: domReady
    http://requirejs.org/docs/errors.html#scripterror
    at /home/mark/sandbox/angularjs-requirejs-seed/node_modules/karma-requirejs/lib/require.js:138
PhantomJS 1.9.1 (Linux): Executed 0 of 0 ERROR (0.238 secs / 0 secs)
Warning: Task "karma:ci" failed. Use --force to continue.

Aborted due to warnings.

**Comment by iwein** [comment]
I've had a look with Dmitry yesterday, but apparently the combination of Grunt, karma and requirejs is trickier than I hoped for. This is going to take a bit more time.

**Comment by dmitryevseev** [comment]
@markfink Thanks again for the call. It's fixed now
