### ISSUE TITLE
Using zurb foundation in this project

### ISSUE THREAD

**Issue by mort3za** [StarterSquad/ngseed#22]
I tried to install foundation by this gulpfile (using gulp-ruby-sass and gulp-sass and foundation --libsass). but it failed. can you help me how to configure gulpfile and place of foundation files?

I also have another question. how can i start a local server to see results using this gulpfile?

Many Thanks

**Comment by mort3za** [comment]
Foundation compiling problem solved.
gulpfile settings that i used:

```
var sass2 = require('gulp-sass');

// Compile Sass
gulp.task('sass2', function() {
    gulp.src(['source/sass/foundation/*.scss', '!source/sass/foundation/_*.scss'])
        .pipe(plumber())
        .pipe(sass2({
            includePaths: ['source/sass/foundation', 'source/vendor/foundation/scss'],
            outputStyle: 'expanded'
        }))
        .pipe(autoprefix(
            "last 1 version", "> 1%", "ie 8"
        ))
        // .pipe(gulp.dest('source/assets/css'))
        // .pipe(minifycss())
        .pipe(gulp.dest('source/assets/css'))
        .pipe(livereload(server));
});
```

but what about starting a http server?

**Comment by mort3za** [comment]
`https://github.com/avevlad/gulp-connect` made my day.

**Comment by dmitryevseev** [comment]
@Mort3ZA I'd better installed foundation sources with bower and included it through sass project itself as the part of `reset` layer, in `/reset` folder

**Comment by mort3za** [comment]
@dmitryevseev yes, it's installed through bower and only app.scss and _settings.scss files are in that folder. i'll move them, but including them through `sass` task raised an error (don't remember what error) and i had to use gulp-sass plugin.
