### ISSUE TITLE
doesnt work on windows 8 (even after you get git and ruby developer kit installed)

### ISSUE THREAD

**Issue by pilavdzic** [StarterSquad/ngseed#31]
In order to use this starter kit you have to divine what is needed and install many things not even mentioned in the install instructions. Only then do you discover that it doesn't work, by running into issues like: 
https://github.com/chriseppstein/sass-globbing/issues/3 

I was hoping a starter kit that includes require and sass which I liked would make starting up easy, but now I have to add these things myself because this won't work (and I don't want all developers to have to install ruby, I know it was popular in 2005 but its now almost 10 years later.. seriously why would anyway want all these megabytes of legacy stuff in their projects?). I downloaded all the dependencies for this seed and it was over 70MB, most of it not that neccessary, like sass globbing. 

This was one of the better seed projects but if I can't get into all these niggly issues when I just want to get started.

![image](https://cloud.githubusercontent.com/assets/976985/4312404/86ca9504-3eb9-11e4-8f8c-291900c4de15.png)

**Comment by julesbou** [comment]
@pilavdzic did you try using a double star `@import 'functions/**';`, as suggested here https://github.com/chriseppstein/sass-globbing/issues/3#issuecomment-22934980 ? Let us know if that work.

**Comment by borodean** [comment]
Ruby is not needed for the latest `develop`. /cc @dmitryevseev @Maqsim

**Comment by pilavdzic** [comment]
Awesome, thanks. I'll try it again after the holidays and let you know if it goes smoother. The parts of this that I got working last time looked very promising and well put together so I'm looking forward to giving it another go.

**Comment by pilavdzic** [comment]
The latest develop as of today I am still having trouble getting to work on Windows (7). Followed the install instructions, but when I try to run gulp I get:

![image](https://cloud.githubusercontent.com/assets/976985/5670298/a42a3ba4-974c-11e4-8a49-3643188f8275.png)

cannot find module lodash.noop

Any particular version of npm required, I am running 1.3.14?

Anyone have any idea how to debug this, I am unfamiliar with what this likely means.

**Comment by dmitryevseev** [comment]
@pilavdzic Sorry about too late, what node version you were using?

**Comment by dmitryevseev** [comment]
There is no ruby dependency anymore. I'll close the issue
